### ISSUE TITLE
Manually added jobs not showing up as running, only when finished

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/pulse_actions#81] opened 2016-05-26 12:56 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1275885

https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&autoclassify&fromchange=b3b9c70d53be4fbfb38f59cd0619984a3cc6d91c&filter-resultStatus=testfailed&filter-resultStatus=busted&filter-resultStatus=exception&filter-resultStatus=retry&filter-resultStatus=usercancel&filter-resultStatus=runnable&filter-resultStatus=success&filter-searchStr=888715a6f2f6acfe351d1fa6b3c08251dd70a039&tochange=10db03f821c4a9bf76d1e516c32eb3c9317aed27&selectedJob=28748516

I tried to backfill these failing Windows XP opt dt1 jobs and also requested them manually on some of these pushes, but they don't show up as pending after waiting for more than 20 minutes. They eventually showed up after they finished.

According to emorley, it's likely that treeherder doesn't see the pulse actions.

**Comment by edmorley** [comment] 2016-05-26 13:00
> According to emorley, it's likely that treeherder doesn't see the pulse actions.

That's not actually what I said :-)

What I meant by https://bugzilla.mozilla.org/show_bug.cgi?id=1275885#c1 was (in more detail):
"The Treeherder team (or at least me) doesn't really understand pulse_actions and how backfilling really works, nor do we have an understanding or how to debug these issues. Plus in many cases I think the problems haven't been with the Treeherder parts. As such, best to file issues against pulse_actions (or wherever appropriate), as bugs filed in Treeherder components may just end up sitting there, since only Treeherder devs will seem them, or are less able to help."

**Comment by martiansideofthemoon** [comment] 2016-05-26 15:21
@armenzg What should be the expected behavior here?

**Comment by armenzg** [comment] 2016-05-26 18:27
One day we will have a job that will reveal the logs but for now this is what I do.

1 - Find the pulse_actions papertrail logs - https://dashboard-preview.heroku.com/apps/pulse-actions
2 - Search for the person trying to schedule something and read the log to see what's going on

From looking at the logs it seems that it all was scheduled.

We could also be having delays in the pipeline (which we can't measure easily).
Here are some areas where this could happen:
- delay between the user requesting the action and TH publishing the message
- delay between Pulse message to being consumed
- delay between message being consumed and finish processing it
  - e.g. one of the requests took 59.3078241348 seconds to execute
- delay between scheduling TaskCluster tasks and the Buildbot bridge kicking in
- delay from adding job to Buildbot's database to showing up on pending.js
- delay from TH picking new info on pending.js

Adding new jobs took an awful long time and the log do not show much (I will need to add debug logging or try locally):
May 26 05:04:40 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 New jobs requested by archaeopteryx@coole-files.de for https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=e8e7a969b8efcdb96d63334a517c394b7e379c9c 
May 26 05:04:40 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 List of builders: 
May 26 05:04:40 pulse-actions app/worker2.1: pulse_actions.handlers.treeherder_runnable	 INFO:	 - Windows XP 32-bit mozilla-inbound opt test mochitest-devtools-chrome-1 
May 26 05:07:15 pulse-actions app/worker2.1: root	 INFO:	 Message {u'version': 1, u'requester': u'archaeopteryx@coole-files.de', u'resultset_id': u'32374', u'buildernames': [u'Windows XP 32-bit mozilla-inbound opt test mochitest-devtools-chrome-1'], u'project': u'mozilla-inbound'}, took 155.293160915 seconds to execute

**Comment by armenzg** [comment] 2016-05-26 18:32
@bhearsum Hey Ben, this push shows 2 buildbot jobs:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=88b6b3ebf75d8356b4ba16c2a65b46b976589dad&filter-searchStr=Windows%20XP%20mochitest-devtools-chrome-1

However, Buildapi shows 3 jobs:
https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/build/112313424
https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/build/112270912
https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/build/112313140

It seems that we're not seeing tasks scheduled by Buildbot Bridge.

Could you please look into this?

**Comment by armenzg** [comment] 2016-05-27 16:04
If I look at this revision [1] I see a third job which is purple. This job has no logs. It did not run (" Not started (queued for 1,126 minute(s)) ")

However, buildapi believes it run for 40 minutes or so.

I think Treeherder missed the end time and that is why it shows it as purple instead of orange.

@edmorley how does Treeherder detects jobs ending?

[1] https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=88b6b3ebf75d8356b4ba16c2a65b46b976589dad&filter-searchStr=Windows%20XP%2032-bit%20mozilla-inbound%20opt%20test%20mochitest-devtools-chrome-1&selectedJob=28786306
[2] https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/88b6b3ebf75d8356b4ba16c2a65b46b976589dad

**Comment by edmorley** [comment] 2016-05-27 16:08
> @edmorley how does Treeherder detects jobs ending?

They'll be imported via builds-4hr and the job updated in Treeherder.
The job in question is pink in Treeherder, which means the user cancelled. If they did so whilst it was in the pending state, we never see it in builds-4hr. Unfortunately at the moment we pre-emptively mark is as cancelled to try and work around that, but the handling could be better - bug 1163802). Whether that's a contributing factor here or not, I'm not sure.

**Comment by armenzg** [comment] 2016-05-30 14:19
I think this could have been a delay on showing jobs or pulse_actions delaying too long to process.
This is not trivial to figure out. I will have to close it for now.

**Closed by armenzg** 2016-05-30 14:19 UTC
